version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:17.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_service
    ports:
      - "5433:5432"
    volumes:
      - /c/Users/surya/Documents/workspace/order-service/docker/postgres:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql